POST http://localhost:3000/registerAdmin
Content-Type: application/json

{
    "username":"A_1",
    "password":"1234",
    "name":"Boss",
    "email":"Boss@gmail.com",
    "phoneNumber":"0123456789",
    "role":"Admin"
}

###
POST http://localhost:3000/login1
Content-Type: application/json

{
    "username":"V_1",
    "password":"1234"
}

###
POST http://localhost:3000/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDhlY2I4ZmY1MGMzNzIzNTNhYmY1NDkiLCJ1c2VybmFtZSI6IkhfMSIsInBhc3N3b3JkIjoiJDJiJDEwJHIzVHhjTUI2eFVnTGwzSGRBU0VPRGVaWlNMTXNTTi92S05KVGo3Y0t2d2t2cGpCM0xuS0FDIiwibmFtZSI6IkVtcGxveWVlcjEiLCJlbWFpbCI6IkVtcGxveWVlMUBnbWFpbC5jb20iLCJyb2xlIjoiSG9zdCIsImlhdCI6MTY4NzA3OTgyOCwiZXhwIjoxNjg3MDgzNDI4fQ.d7S8z3foooLjAkj8Hhz5HQUR6zcxR1gTrEba8kBql84
Content-Type: application/json

{
    "username":"V_1",
    "password":"1234",
    "name":"Visitor1",
    "email":"Visitor1@gmail.com",
    "phoneNumber":"0123456789"
}

###
GET http://localhost:3000/read
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDhlY2JjZWI1NTUzNDExMjliMjkxYTMiLCJ1c2VybmFtZSI6IlZfMSIsInBhc3N3b3JkIjoiJDJiJDEwJDg2dHBMNkZ3d1JVNmM2Ri5iSjdnQWV3cWxaU2xiRUpSWmJRMDJHVERaL0JMR3Zpd2tnM25PIiwibmFtZSI6IlZpc2l0b3IxIiwiZW1haWwiOiJWaXNpdG9yMUBnbWFpbC5jb20iLCJyb2xlIjoiVmlzaXRvciIsImhvc3QiOiJIXzEiLCJyZWNvcmRzIjpbIlJfMSJdLCJpYXQiOjE2ODcwODAwNDAsImV4cCI6MTY4NzA4MzY0MH0.hIqiAYqkgrYrANniGGM5NbPZ6be3QXv0Jhk0ljNYdhs

###
PATCH http://localhost:3000/update
Authorization: Bearer 
Content-Type: application/json

{
    "email":"Visitor5@gmail.com",
    "name": "Visitor5"
}

###
DELETE http://localhost:3000/deleteUser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDhiYzc1YTQyMjMzZTM1MGRjOWFkOTkiLCJ1c2VybmFtZSI6IlZfMyIsInBhc3N3b3JkIjoiMTIzNCIsIm5hbWUiOiJWaXNpdG9yMyIsImVtYWlsIjoiVmlzaXRvcjNAZ21haWwuY29tIiwicm9sZSI6IlZpc2l0b3IiLCJob3N0IjoiSF8xIiwiaWF0IjoxNjg2ODgyMTYxLCJleHAiOjE2ODY4ODU3NjF9.MMzpuwuie8hvuAOkcBEhYRdgkWY3OEI_neUEHEVnucc

###
POST http://localhost:3000/checkIn
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDhlY2JjZWI1NTUzNDExMjliMjkxYTMiLCJ1c2VybmFtZSI6IlZfMSIsInBhc3N3b3JkIjoiJDJiJDEwJDg2dHBMNkZ3d1JVNmM2Ri5iSjdnQWV3cWxaU2xiRUpSWmJRMDJHVERaL0JMR3Zpd2tnM25PIiwibmFtZSI6IlZpc2l0b3IxIiwiZW1haWwiOiJWaXNpdG9yMUBnbWFpbC5jb20iLCJyb2xlIjoiVmlzaXRvciIsImhvc3QiOiJIXzEiLCJyZWNvcmRzIjpbIlJfMSIsIlJfMiJdLCJjdXJyZW50Q2hlY2tJbiI6IlJfMiIsImlhdCI6MTY4NzA4MTM1MSwiZXhwIjoxNjg3MDg0OTUxfQ.1E2Ccu_fvGJeIbrGQItOCXJms6q-gK9ctoiHBV97zpE
Content-Type: application/json

{
    "recordID":"R_2",
    "purpose":"Visit"
}

###
PATCH http://localhost:3000/checkOut
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDhlY2JjZWI1NTUzNDExMjliMjkxYTMiLCJ1c2VybmFtZSI6IlZfMSIsInBhc3N3b3JkIjoiJDJiJDEwJDg2dHBMNkZ3d1JVNmM2Ri5iSjdnQWV3cWxaU2xiRUpSWmJRMDJHVERaL0JMR3Zpd2tnM25PIiwibmFtZSI6IlZpc2l0b3IxIiwiZW1haWwiOiJWaXNpdG9yMUBnbWFpbC5jb20iLCJyb2xlIjoiVmlzaXRvciIsImhvc3QiOiJIXzEiLCJyZWNvcmRzIjpbIlJfMSIsIlJfMiJdLCJjdXJyZW50Q2hlY2tJbiI6IlJfMiIsImlhdCI6MTY4NzA4MTM1MSwiZXhwIjoxNjg3MDg0OTUxfQ.1E2Ccu_fvGJeIbrGQItOCXJms6q-gK9ctoiHBV97zpE
