POST http://localhost:3000/registerAdmin
Content-Type: application/json

{
    "username":"A_1",
    "password":"1234",
    "name":"Boss",
    "email":"Boss@gmail.com",
    "phoneNumber":"0123456789",
    "role":"Admin"
}

###
POST http://localhost:3000/login1
Content-Type: application/json

{
    "username":"A_1",
    "password":"1234"
}

###
POST http://localhost:3000/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDkzZWZjNzFkZDA4MGNlNWNiZDU2ZjEiLCJ1c2VybmFtZSI6IkFfMSIsInBhc3N3b3JkIjoiJDJiJDEwJEQ2ZjRLVnpPbzhwVlYyRnVPUS9UaC5kMWcwUWgzV0ptb0VFVVVlYzZxYURKRER6dlI3WkdhIiwibmFtZSI6IkJvc3MiLCJlbWFpbCI6IkJvc3NAZ21haWwuY29tIiwicGhvbmVOdW1iZXIiOiIwMTIzNDU2Nzg5Iiwicm9sZSI6IkFkbWluIiwiaWF0IjoxNjg3NDE3ODUyLCJleHAiOjE2ODc0MjE0NTJ9.hUWruG0ox_mCYreY3S0kYewu-gxg9WG6M33N8wwla8I
Content-Type: application/json

{
    "username":"H_1",
    "password":"1234",
    "name":"Host1",
    "email":"Host1@gmail.com",
    "phoneNumber":"0123456789"
}

###
POST http://localhost:3000/login1
Content-Type: application/json

{
    "username":"H_1",
    "password":"1234"
}

###
POST http://localhost:3000/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDkzZjQ5ZDQ4YjY3ZTQzOTJlY2IzOWQiLCJ1c2VybmFtZSI6IkhfMiIsInBhc3N3b3JkIjoiJDJiJDEwJGxTTjBjWlFnTTRQRThOYlNuUnVUbXViWjFwdEZkN2pIa2tBOGtTcmpXMDczSGtTVDEuQkRxIiwibmFtZSI6Ikhvc3QyIiwiZW1haWwiOiJIb3N0MkBnbWFpbC5jb20iLCJyb2xlIjoiSG9zdCIsInZpc2l0b3JzIjpbXSwiaWF0IjoxNjg3NDE4MDI1LCJleHAiOjE2ODc0MjE2MjV9.FF2czFkrMr_uul-gdSXKAguisOo3LK2Ph3J6deVKRUM
Content-Type: application/json

{
    "username":"V_1",
    "password":"1234",
    "name":"Visitor1",
    "email":"Visitor1@gmail.com",
    "phoneNumber":"0123456789"
}

###
POST http://localhost:3000/login1
Content-Type: application/json

{
    "username":"V_1",
    "password":"1234"
}

###
GET http://localhost:3000/read
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDkzZjA1ZTFjNzY1MmUxNWM4Y2FlMTciLCJ1c2VybmFtZSI6IlZfMSIsInBhc3N3b3JkIjoiJDJiJDEwJE1KRk4vdHVwb2RjUnB3RFNmVy9Kdy5iQlpjaWVucktnVU5TYVo2RTRydnlUWVlNaFdGSEJhIiwibmFtZSI6IlZpc2l0b3IxIiwiZW1haWwiOiJWaXNpdG9yMUBnbWFpbC5jb20iLCJyb2xlIjoiVmlzaXRvciIsImhvc3QiOiJIXzEiLCJyZWNvcmRzIjpbIlJfMSIsIlJfMiJdLCJpYXQiOjE2ODc0MTc2NzIsImV4cCI6MTY4NzQyMTI3Mn0.Cfwq5cyxxWGF5sZxxDCc1AwLzCYiWswdTSjMMpkOqSo

###
PATCH http://localhost:3000/update
Authorization: Bearer 
Content-Type: application/json

{
    "email":"Visitor2@gmail.com",
    "name": "Visitor2"
}

###
DELETE http://localhost:3000/deleteUser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDhmYTlhMzk2NThlZTgzMjM2NzRjZTQiLCJ1c2VybmFtZSI6IlZfNSIsInBhc3N3b3JkIjoiJDJiJDEwJHlaVndyMVJVUWd2eDlsWTVyaHNvYS5wSVg4WnRrQWlESTMzaVhoOWZFSXFvTXM5WDdZdFlTIiwibmFtZSI6IlZpc2l0b3I1IiwiZW1haWwiOiJWaXNpdG9yNUBnbWFpbC5jb20iLCJyb2xlIjoiVmlzaXRvciIsImhvc3QiOiJIXzIiLCJyZWNvcmRzIjpbIlJfNSIsIlJfNiJdLCJpYXQiOjE2ODcxNDUyMzQsImV4cCI6MTY4NzE0ODgzNH0.4oA9A0-2hD1TEuRmF5M2bjVuKbxDLkuKNBd5qvZg43E

###
POST http://localhost:3000/checkIn
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDkzZjRiNTQ4YjY3ZTQzOTJlY2IzOWUiLCJ1c2VybmFtZSI6IlZfMyIsInBhc3N3b3JkIjoiJDJiJDEwJFdULk5ZRWhPY2Zta1p2Nmk3NlE5MmVhenNlWDEyUG1SVGhTZHZZdHZKWDlJVWJBQXBlcXB1IiwibmFtZSI6IlZpc2l0b3IyIiwiZW1haWwiOiJWaXNpdG9yMkBnbWFpbC5jb20iLCJyb2xlIjoiVmlzaXRvciIsImhvc3QiOiJIXzIiLCJyZWNvcmRzIjpbXSwiaWF0IjoxNjg3NDE4MDU2LCJleHAiOjE2ODc0MjE2NTZ9.cJijtMuYtSpAresRJ6GT6U5NlL6lWURP3cAjPHDLYZs
Content-Type: application/json

{
    "recordID":"R_1",
    "purpose":"Visit"
}

###
PATCH http://localhost:3000/checkOut
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDkzZjRiNTQ4YjY3ZTQzOTJlY2IzOWUiLCJ1c2VybmFtZSI6IlZfMyIsInBhc3N3b3JkIjoiJDJiJDEwJFdULk5ZRWhPY2Zta1p2Nmk3NlE5MmVhenNlWDEyUG1SVGhTZHZZdHZKWDlJVWJBQXBlcXB1IiwibmFtZSI6IlZpc2l0b3IyIiwiZW1haWwiOiJWaXNpdG9yMkBnbWFpbC5jb20iLCJyb2xlIjoiVmlzaXRvciIsImhvc3QiOiJIXzIiLCJyZWNvcmRzIjpbXSwiaWF0IjoxNjg3NDE4MDU2LCJleHAiOjE2ODc0MjE2NTZ9.cJijtMuYtSpAresRJ6GT6U5NlL6lWURP3cAjPHDLYZs

###
POST http://localhost:3000/checkIn
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDkzZjA1ZTFjNzY1MmUxNWM4Y2FlMTciLCJ1c2VybmFtZSI6IlZfMSIsInBhc3N3b3JkIjoiJDJiJDEwJE1KRk4vdHVwb2RjUnB3RFNmVy9Kdy5iQlpjaWVucktnVU5TYVo2RTRydnlUWVlNaFdGSEJhIiwibmFtZSI6IlZpc2l0b3IxIiwiZW1haWwiOiJWaXNpdG9yMUBnbWFpbC5jb20iLCJyb2xlIjoiVmlzaXRvciIsImhvc3QiOiJIXzEiLCJyZWNvcmRzIjpbXSwiaWF0IjoxNjg3NDE2OTMwLCJleHAiOjE2ODc0MjA1MzB9.ahQfsuke-UWu3ytbovlx2aylo3DuLxZyI3kMzNWhYdY
Content-Type: application/json

{
    "recordID":"R_2",
    "purpose":"Visit"
}

###
PATCH http://localhost:3000/checkOut
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDkzZjA1ZTFjNzY1MmUxNWM4Y2FlMTciLCJ1c2VybmFtZSI6IlZfMSIsInBhc3N3b3JkIjoiJDJiJDEwJE1KRk4vdHVwb2RjUnB3RFNmVy9Kdy5iQlpjaWVucktnVU5TYVo2RTRydnlUWVlNaFdGSEJhIiwibmFtZSI6IlZpc2l0b3IxIiwiZW1haWwiOiJWaXNpdG9yMUBnbWFpbC5jb20iLCJyb2xlIjoiVmlzaXRvciIsImhvc3QiOiJIXzEiLCJyZWNvcmRzIjpbXSwiaWF0IjoxNjg3NDE2OTMwLCJleHAiOjE2ODc0MjA1MzB9.ahQfsuke-UWu3ytbovlx2aylo3DuLxZyI3kMzNWhYdY